export const GET_PRODUCTS = "GET_PRODUCTS";
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const POST_BOLICHE = "POST_BOLICHES";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
